# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import sp3d.storage_backends
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organisation_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=sp3d.storage_backends.PrivateMediaStorage(bucket=b'sp3d-users'), upload_to=users.models.get_logo_path),
        ),
    ]
