# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 05:57
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0008_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
