# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0009_organisation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
