# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import sp3d.storage_backends
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171130_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=sp3d.storage_backends.PrivateMediaStorage(bucket=b'sp3d-users'), upload_to=users.models.get_profile_pic_path),
        ),
    ]
