# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp3d_part',
            name='part_id',
            field=models.IntegerField(default=0),
        ),
    ]
