# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20170621_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_id', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.SP3D_Part')),
            ],
        ),
    ]
