# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20170621_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_part',
            name='amf',
        ),
        migrations.RemoveField(
            model_name='sp3d_part',
            name='config',
        ),
        migrations.RemoveField(
            model_name='sp3d_part',
            name='oem_number',
        ),
    ]
