# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20170621_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='amf',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='config',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='oem_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
