# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20170621_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_part',
            name='part_id',
        ),
    ]
