# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_remove_sp3d_part_part_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('printer_id', models.IntegerField(default=0)),
                ('printer_name', models.CharField(default='Printer001', max_length=200)),
                ('oem_number', models.CharField(default='', max_length=200)),
                ('amf', models.CharField(default='', max_length=200)),
                ('log_id', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
            ],
        ),
    ]
