# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_sp3d_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_print',
            name='printer_name',
        ),
    ]
