# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_remove_sp3d_print_printer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Printer001', max_length=200)),
                ('location', models.CharField(default='SP3D Office Singapore', max_length=200)),
            ],
        ),
    ]
