# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_sp3d_printer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_print',
            old_name='printer_id',
            new_name='id_part',
        ),
        migrations.RemoveField(
            model_name='sp3d_print',
            name='oem_number',
        ),
        migrations.AddField(
            model_name='sp3d_print',
            name='id_printer',
            field=models.IntegerField(default=0),
        ),
    ]
