# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_auto_20170701_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_print',
            name='amf',
        ),
    ]
