# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_remove_sp3d_print_amf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_printer',
            name='local_ip',
            field=models.CharField(default='', max_length=200),
        ),
    ]
