# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_sp3d_printer_local_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='gcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
