# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_sp3d_part_gcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_part',
            name='gcode',
        ),
    ]
