# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_remove_sp3d_part_gcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='gcode',
            field=models.IntegerField(default=0),
        ),
    ]
