# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_sp3d_part_gcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp3d_part',
            name='amf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sp3d_part',
            name='config',
            field=models.IntegerField(default=0),
        ),
    ]
