# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20170706_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/files/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_part', models.IntegerField(default=0)),
            ],
        ),
    ]
