# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_sp3d_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Oem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Spare Parts 3D', max_length=200)),
                ('code', models.CharField(default='SP3D', max_length=100)),
            ],
        ),
    ]
