# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_sp3d_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='id_oem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='part_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sp3d_image',
            name='root_path',
            field=models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200),
        ),
    ]
