# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_auto_20170711_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_part',
            name='done',
        ),
    ]
