# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_remove_sp3d_part_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_CAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_part', models.IntegerField(default=0)),
                ('id_creator', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sp3d_image',
            name='id_creator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='id_creator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_print',
            name='id_creator',
            field=models.IntegerField(default=0),
        ),
    ]
