# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20170711_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_AMF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_part', models.IntegerField(default=0)),
                ('id_creator', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SP3D_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_part', models.IntegerField(default=0)),
                ('id_creator', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='sp3d_cad',
            name='is_oem_cad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_cad',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_image',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_iteration',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_oem',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_print',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sp3d_printer',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
