# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20170712_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_part',
            old_name='oem_number',
            new_name='oem_name',
        ),
    ]
