# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_auto_20170717_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='permissions',
            field=models.CharField(default='', max_length=200),
        ),
    ]
