# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_sp3d_3mf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='checked_out',
            field=models.IntegerField(default=0),
        ),
    ]
