# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_sp3d_stl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_3mf',
            name='gcode_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sp3d_3mf',
            name='name_gcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
