# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_auto_20170724_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_cad',
            name='first_config',
            field=models.IntegerField(default=0),
        ),
    ]
