# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0030_sp3d_cad_first_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='checked_out_by',
            field=models.IntegerField(default=0),
        ),
    ]
