# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_sp3d_part_checked_out_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_print',
            name='id_3mf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_print',
            name='id_cad',
            field=models.IntegerField(default=0),
        ),
    ]
