# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0032_auto_20170727_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_CAD2D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_cad', models.IntegerField(default=0)),
                ('id_creator', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
