# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0033_sp3d_cad2d'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_part',
            name='part_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
