# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0035_sp3d_part_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Status_Eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SP3D_Status_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('from_status', models.IntegerField(default=0)),
                ('to_status', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='sp3d_part',
            name='status',
        ),
        migrations.AddField(
            model_name='sp3d_part',
            name='status_eng',
            field=models.IntegerField(default=0),
        ),
    ]
