# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0036_auto_20170731_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_status_history',
            name='id_creator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sp3d_status_history',
            name='to_status',
            field=models.IntegerField(default=1),
        ),
    ]
