# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0038_auto_20170801_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SP3D_Status_History',
            new_name='SP3D_Status_Eng_History',
        ),
    ]
