# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0039_auto_20170802_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_status_eng_history',
            old_name='to_status',
            new_name='id_status',
        ),
        migrations.RemoveField(
            model_name='sp3d_status_eng_history',
            name='from_status',
        ),
    ]
