# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0041_sp3d_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_profile',
            old_name='slack_webhook',
            new_name='slack_name',
        ),
    ]
