# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_sp3d_bulk_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_print',
            name='finished_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
