# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0045_sp3d_print_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp3d_print',
            name='finished_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
