# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0046_auto_20170804_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_print',
            name='printing_time',
            field=models.IntegerField(null=True),
        ),
    ]
