# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0048_sp3d_part_oem_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('adress', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=20)),
                ('activity', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SP3D_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(default='', max_length=200)),
                ('id_type', models.CharField(default='', max_length=200)),
                ('id_client', models.IntegerField(default=0)),
                ('quote_number', models.CharField(default='', max_length=200)),
                ('po_number', models.CharField(default='', max_length=200)),
                ('due_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('assigned_to', models.IntegerField(default=0)),
                ('root_path', models.CharField(default='', max_length=200)),
                ('parts', models.CharField(default='', max_length=200)),
                ('quantities', models.CharField(default='', max_length=200)),
                ('id_creator', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('permissions', models.CharField(default='', max_length=200)),
                ('status_ord', models.IntegerField(default=1)),
            ],
        ),
    ]
