# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0049_sp3d_client_sp3d_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_client',
            name='code',
        ),
    ]
