# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0050_remove_sp3d_client_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_client',
            old_name='adress',
            new_name='address',
        ),
    ]
