# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0051_auto_20170807_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_client',
            old_name='email',
            new_name='primary_contact_email',
        ),
        migrations.AddField(
            model_name='sp3d_client',
            name='primary_contact_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
