# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0052_auto_20170807_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_client',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
