# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0053_sp3d_client_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp3d_order',
            old_name='id_type',
            new_name='type',
        ),
    ]
