# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0054_auto_20170808_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_order',
            name='closed_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_order',
            name='completion_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
