# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0055_auto_20170808_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_order',
            name='quantities',
        ),
    ]
