# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0057_auto_20170810_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_bulk_files',
            name='id_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sp3d_bulk_files',
            name='id_creator',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
