# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0058_auto_20170810_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Po_Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('id_client', models.CharField(default='', max_length=200)),
                ('id_order', models.IntegerField(default=0, null=True)),
                ('client_contact', models.IntegerField(null=True)),
                ('revision', models.IntegerField(default=0)),
                ('po_number', models.CharField(default='', max_length=200)),
                ('parts', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_creator', models.IntegerField(default=0, null=True)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SP3D_Quote_Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('id_client', models.CharField(default='', max_length=200)),
                ('id_order', models.IntegerField(default=0, null=True)),
                ('client_contact', models.IntegerField(null=True)),
                ('revision', models.IntegerField(default=0)),
                ('quote_number', models.CharField(default='', max_length=200)),
                ('parts', models.CharField(default='', max_length=200)),
                ('root_path', models.CharField(default='/home/user01/SpareParts_Database/root/', max_length=200)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('id_creator', models.IntegerField(default=0, null=True)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
