# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0059_sp3d_po_revision_sp3d_quote_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_po_revision',
            name='currency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sp3d_po_revision',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sp3d_quote_revision',
            name='currency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sp3d_quote_revision',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
