# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0060_auto_20170810_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_client',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
