# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0061_sp3d_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_po_revision',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp3d_quote_revision',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sp3d_order',
            name='status_ord',
            field=models.IntegerField(default=0),
        ),
    ]
