# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0062_auto_20170811_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Status_Ord_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('id_status', models.IntegerField(default=0)),
                ('id_creator', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
