# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0064_sp3d_printer_z_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp3d_printer',
            name='z_offset',
            field=models.FloatField(default=0.1),
        ),
    ]
