# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0065_auto_20170814_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('prefix', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone_perso', models.CharField(default='', max_length=200)),
                ('phone_office', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('id_client', models.IntegerField(default=0)),
                ('notes', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='sp3d_client',
            name='primary_contact_email',
        ),
        migrations.RemoveField(
            model_name='sp3d_client',
            name='primary_contact_name',
        ),
    ]
