# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0066_auto_20170815_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_order',
            name='id_contacts',
            field=models.CharField(default='', max_length=100),
        ),
    ]
