# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0067_sp3d_order_id_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp3d_order',
            name='id_contacts',
        ),
        migrations.AddField(
            model_name='sp3d_order',
            name='id_contact',
            field=models.IntegerField(default=0),
        ),
    ]
