# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0068_auto_20170815_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3D_Status_Ord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
