# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0069_sp3d_status_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_print',
            name='id_bulk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sp3d_order',
            name='status_ord',
            field=models.IntegerField(default=1),
        ),
    ]
