# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0070_auto_20170905_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3d_profile',
            name='slack_hook',
            field=models.TextField(default='', max_length=200),
        ),
    ]
