# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='slack_hook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='slack_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
