# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0002_auto_20171027_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 9, 17, 30, 357139)),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
