# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0003_auto_20171112_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleTechnoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Technology Name')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='family',
            field=models.CharField(choices=[('metal', 'metal'), ('plastic', 'plastic')], max_length=20, null=True, verbose_name='Material Family'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Material Name'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='coupletechnomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jb.Material'),
        ),
        migrations.AddField(
            model_name='coupletechnomaterial',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jb.Technology'),
        ),
        migrations.AddField(
            model_name='material',
            name='technology',
            field=models.ManyToManyField(through='jb.CoupleTechnoMaterial', to='jb.Technology'),
        ),
        migrations.AlterUniqueTogether(
            name='coupletechnomaterial',
            unique_together=set([('material', 'technology')]),
        ),
    ]
