# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0003_auto_20171027_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
