# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0025_auto_20171123_0722'),
        ('jb', '0004_auto_20171123_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupletechnomaterial',
            name='characteristics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Characteristics'),
        ),
    ]
