# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0006_auto_20171123_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0.0, max_length=20, verbose_name='Unit Price')),
                ('currency', models.CharField(choices=[('USD', '$US'), ('SGD', '$SG'), ('EUR', '\u20ac'), ('BTC', 'Bitcoin'), ('ETH', 'Euthereum')], default='USD', max_length=10, verbose_name='Currency')),
                ('lead_time', models.IntegerField(default=0.0, verbose_name='Lead time (days)')),
                ('techno_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jb.CoupleTechnoMaterial')),
            ],
        ),
    ]
