# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0007_finalcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcard',
            name='techno_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jb.CoupleTechnoMaterial', verbose_name='Couple Techno-Material'),
        ),
    ]
