# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0008_auto_20171124_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcard',
            name='lead_time',
            field=models.IntegerField(default=3, verbose_name='Lead time (days)'),
        ),
    ]
