# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0009_auto_20171124_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default='', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(default='', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Short Material Name'),
        ),
    ]
