# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0010_auto_20171127_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Material Description'),
        ),
    ]
