# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0011_auto_20171127_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupletechnomaterial',
            name='characteristics',
        ),
    ]
