# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0012_remove_coupletechnomaterial_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Short Technology Name'),
        ),
    ]
