# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0013_auto_20171128_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='max_X',
            field=models.IntegerField(null=True, verbose_name='Maximum Part X'),
        ),
        migrations.AddField(
            model_name='technology',
            name='max_Y',
            field=models.IntegerField(null=True, verbose_name='Maximum Part Y'),
        ),
        migrations.AddField(
            model_name='technology',
            name='max_Z',
            field=models.IntegerField(null=True, verbose_name='Maximum Part Z'),
        ),
    ]
