# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0043_auto_20171205_0141'),
        ('jb', '0014_auto_20171204_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupletechnomaterial',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techno_material_characteristics', to='digital.Characteristics'),
        ),
        migrations.AddField(
            model_name='material',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_characteristics', to='digital.Characteristics'),
        ),
        migrations.AddField(
            model_name='technology',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_characteristics', to='digital.Characteristics'),
        ),
    ]
