# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0015_auto_20171205_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Technology Description'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='max_X',
            field=models.IntegerField(null=True, verbose_name='Maximum Part X (mm)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='max_Y',
            field=models.IntegerField(null=True, verbose_name='Maximum Part Y (mm)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='max_Z',
            field=models.IntegerField(null=True, verbose_name='Maximum Part Z (mm)'),
        ),
    ]
