# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0045_auto_20171205_0352'),
        ('jb', '0016_auto_20171205_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcard',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_final_card', to='digital.Part'),
        ),
    ]
