# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0018_auto_20171205_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcard',
            name='lead_time',
            field=models.IntegerField(default=10, verbose_name='Lead time (days)'),
        ),
        migrations.AlterField(
            model_name='finalcard',
            name='techno_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jb.CoupleTechnoMaterial', verbose_name='Couple Techno-Material'),
        ),
    ]
